In [48]:
import numpy as np

In [74]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
b = np.arange(8).reshape(2,-1)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
np.vstack((a, b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [80]:
c = np.arange(6).reshape(-1,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
np.hstack((a,c))

array([[ 0,  1,  2,  3,  0,  1],
       [ 4,  5,  6,  7,  2,  3],
       [ 8,  9, 10, 11,  4,  5]])

In [84]:
np.hstack((c, a))

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11]])

In [103]:
c = np.array([1, 3, 5])
c

array([1, 3, 5])

In [105]:
np.hstack((a, c.reshape(3, -1)))

array([[ 0,  1,  2,  3,  1],
       [ 4,  5,  6,  7,  3],
       [ 8,  9, 10, 11,  5]])

In [116]:
a = np.arange(1,5,1).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [118]:
b = np.tile(a, (2,3))
b

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [126]:
b.base

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [130]:
a = np.arange(1,16,1).reshape(3,-1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [132]:
np.delete(a, [1, 3], axis=1)

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [134]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [136]:
a = np.arange(1,9).reshape(2,2,2)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [139]:
b = np.array(
    [
        [[0,0,0,0],
        [0,0,0,0]],
        [[1,1,1,1],
        [1,1,1,1]],
        [[2,2,2,2],
        [2,2,2,2]],            
    ]
)

b

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [142]:
c = np.zeros((3,4,5))
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [144]:
d = np.zeros((4,5,3))

d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])