In [2]:
import numpy as np

# The Basics

In [ ]:
a = np.array([1,2,3], dtype='int32')

In [ ]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

In [ ]:
# Get Dimension
b.ndim

In [ ]:
# Get shape
b.shape

In [ ]:
# Get Type
a.dtype


In [ ]:
# Get size
a.itemsize
b.itemsize

In [ ]:
# Get total size
a.size * a.itemsize
a.nbytes

b.nbytes

## Accessing/ change specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

In [ ]:
a.shape

In [ ]:
# Get a specific element [r, c]
a[1,5]
a[1,-2]

In [ ]:
# Get a specific row
a[0, :]

In [ ]:
# get a specific column
a[:, 2]

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]

a[0, 1:6:2]

In [ ]:
a[1,5] = 20
# print(a)

a[:, 2] = [1,2]
print(a)

## 3-d example

In [ ]:
b = np.array([[[1,2,], [3,4]], [[5,6], [7,8]]])
print(b)

In [ ]:
#get a specific element
b.shape
b[0, 1, 1]

In [ ]:
# replace
b[:,1,:]= [[9,9], [8,8]]

print(b)


# Initializing Different types of arrays

In [6]:
# All 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# ALL 1s matrix

np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
# ALl with other number

np.full((2,2), 99)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

print(a)

In [ ]:
# Random decimal numbers

np.random.rand(4,2)

In [ ]:
# Random integer value
np.random.randint(3, 9, size=(3,3))

In [252]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Mathematics

In [ ]:
a = np.array([1,2,3,4])
a

In [ ]:
a + 2

In [ ]:
a-2


In [ ]:
b = np.array([1,0,1,0])
b

In [ ]:
a+b

In [ ]:
a ** 2

In [ ]:
np.sin(a)

In [ ]:
np.cos(b)

## Linea Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

In [ ]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

## Statistics

In [ ]:
stats = np.array([[1,2,3], [4,5,6,]])
stats

In [ ]:
np.min(stats, axis=1)

In [ ]:
np.max(stats)

In [ ]:
stats[0,1]

In [ ]:
np.sum(stats)

# Reorganizing Arrays

In [262]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)


after = before.reshape((8,1))

print(after)

print(before) # to show that reshape is a deep copy

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]


In [267]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [274]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

np.hstack((h1,h2))
np.hstack((h2,h1))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

# Miscellaneous

##### Load data from file

In [285]:
# Load data from file

filedata = np.genfromtxt('data.txt', delimiter=',')
# filedata.shape
filedata = filedata.astype('int32')

filedata


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### Boolean Masking and Advanced Indexing

In [287]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [288]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [293]:
## you can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])

In [301]:
# any element meet condition, by axis
np.any(filedata > 50, axis=1)
np.any(filedata > 50, axis=0)

# all element meet condtion, by axis
np.all(filedata > 50, axis=1)
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [302]:
# multiple conditions

((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [10]:
quize = np.array(
    [[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25],
        [26,27,28,29,30],]
)

quize

quize[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [17]:
a = 472 / 709
print(a)

c = 472 / 0.6
print(c)

0.6657263751763046
786.6666666666667


In [15]:
b = 4 / 6
b

0.6666666666666666